// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mixmodel_Rcpp
List mixmodel_Rcpp(NumericVector X, int K, int times, NumericVector initial_tau, NumericVector initial_mu, NumericVector initial_sigma);
RcppExport SEXP _SA22204174_mixmodel_Rcpp(SEXP XSEXP, SEXP KSEXP, SEXP timesSEXP, SEXP initial_tauSEXP, SEXP initial_muSEXP, SEXP initial_sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type times(timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_tau(initial_tauSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_mu(initial_muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial_sigma(initial_sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(mixmodel_Rcpp(X, K, times, initial_tau, initial_mu, initial_sigma));
    return rcpp_result_gen;
END_RCPP
}
// mcmc_Gibbs_Rcpp
NumericMatrix mcmc_Gibbs_Rcpp(double a, double b, double n, NumericVector initial, int N);
RcppExport SEXP _SA22204174_mcmc_Gibbs_Rcpp(SEXP aSEXP, SEXP bSEXP, SEXP nSEXP, SEXP initialSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type initial(initialSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmc_Gibbs_Rcpp(a, b, n, initial, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA22204174_mixmodel_Rcpp", (DL_FUNC) &_SA22204174_mixmodel_Rcpp, 6},
    {"_SA22204174_mcmc_Gibbs_Rcpp", (DL_FUNC) &_SA22204174_mcmc_Gibbs_Rcpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA22204174(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
